[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddTorrentStopped=false
Session\DefaultSavePath=/downloads/
Session\Port=6882
Session\QueueingSystemEnabled=true
Session\SSL\Port=41269
Session\ShareLimitAction=Stop
Session\TempPath=/downloads/incomplete/

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
PortForwardingEnabled=false
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
WebUI\Address=127.0.0.1
WebUI\LocalHostAuth=false
WebUI\Port=8080
WebUI\ServerDomains=*
WebUI\Username=admin
WebUI\Password_PBKDF2="@ByteArray(c2VlZGJyci1hZG1pbmFkbWlu:BmHi4fDZSS+duv4oN5kESPUfla71RD4GGfWaR4C2w1I7Xc7bshPceodulo8DUS0PZMQz2tR7jhkywlkg3zD50A==)"
